"""Generate compatibility instruction files for common coding agents."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path


GENERATED_MARKER = "Generated by godogen publish.sh."
COMMON_PROMPT = (
    "Follow the repository root `AGENTS.md`. For game generation or update "
    "requests, read `.agents/skills/godogen/SKILL.md` first if this tool does "
    "not load repository skills automatically."
)


@dataclass(frozen=True)
class CompatFile:
    rel_path: str
    content: str
    modes: frozenset[str]


def generated_comment() -> str:
    return (
        f"<!-- {GENERATED_MARKER} Edit AGENTS.md in this repo to change "
        "Godogen runtime instructions. -->"
    )


def godogen_md(engine: str) -> str:
    support_skill = "godot-api" if engine == "godot" else "bevy-help"
    support_purpose = (
        "targeted Godot class APIs or C# Godot syntax"
        if engine == "godot"
        else "Bevy APIs, examples, or architecture help"
    )
    return f"""# Godogen Runtime

{generated_comment()}

Use Godogen to generate or update this {engine.capitalize()} game from a natural-language description.

## Start Here

- Canonical repo instruction file: `AGENTS.md`
- Main runtime skill: `.agents/skills/godogen/SKILL.md`
- Engine support skill: `.agents/skills/{support_skill}/SKILL.md`

If this AI tool supports repository skills, invoke `godogen`. Otherwise, read `.agents/skills/godogen/SKILL.md` and follow its staged pipeline.

Use `{support_skill}` for {support_purpose}. If the skill is not available in the tool, read `.agents/skills/{support_skill}/SKILL.md` directly.

## Durable State

Keep run state in `PLAN.md`, `STRUCTURE.md`, `ASSETS.md`, and `MEMORY.md` so another agent can resume from files instead of chat history.
"""


def compat_files(engine: str) -> list[CompatFile]:
    comment = generated_comment()
    return [
        CompatFile(
            "GODOGEN.md",
            godogen_md(engine),
            frozenset({"minimal", "full"}),
        ),
        CompatFile(
            "opencode.jsonc",
            """{
  "$schema": "https://opencode.ai/config.json",
  "//": "Generated by godogen publish.sh. Edit AGENTS.md in this repo to change Godogen runtime instructions.",
  "instructions": [
    "AGENTS.md",
    "GODOGEN.md",
    ".agents/skills/godogen/SKILL.md"
  ]
}
""",
            frozenset({"minimal", "full"}),
        ),
        CompatFile("CLAUDE.md", f"{comment}\n\n@./AGENTS.md\n", frozenset({"full"})),
        CompatFile("GEMINI.md", f"{comment}\n\n@./AGENTS.md\n", frozenset({"full"})),
        CompatFile(
            ".cursor/rules/godogen.mdc",
            f"""---
alwaysApply: true
---

{comment}

{COMMON_PROMPT}
""",
            frozenset({"full"}),
        ),
        CompatFile(
            ".clinerules/godogen.md",
            f"{comment}\n\n{COMMON_PROMPT}\n",
            frozenset({"full"}),
        ),
        CompatFile(
            ".windsurf/rules/godogen.md",
            f"{comment}\n\n{COMMON_PROMPT}\n",
            frozenset({"full"}),
        ),
        CompatFile(
            ".continue/rules/godogen.md",
            f"""---
name: Godogen Runtime
description: Load Godogen instructions for game generation and updates.
---

{comment}

{COMMON_PROMPT}
""",
            frozenset({"full"}),
        ),
    ]


def write_file(target: Path, entry: CompatFile, dry_run: bool) -> None:
    path = target / entry.rel_path

    if (
        entry.rel_path == "opencode.jsonc"
        and (target / "opencode.json").is_file()
        and not path.exists()
    ):
        print("Preserved existing opencode.json; skipped opencode.jsonc")
        return

    if path.is_file():
        text = path.read_text()
        if GENERATED_MARKER not in text:
            print(f"Preserved existing {entry.rel_path}")
            return
        action = "Would update" if dry_run else "Updated"
    else:
        action = "Would create" if dry_run else "Created"

    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(entry.content)
    print(f"{action} {entry.rel_path}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", required=True, type=Path)
    parser.add_argument("--engine", required=True, choices=["godot", "bevy"])
    parser.add_argument(
        "--mode", required=True, choices=["none", "minimal", "full"]
    )
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    if args.mode == "none":
        print("Agent compatibility files disabled")
        return 0

    for entry in compat_files(args.engine):
        if args.mode in entry.modes:
            write_file(args.target, entry, args.dry_run)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
